<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Dokpod.ControlPlane.Application/Dokpod.ControlPlane.Application.csproj" />
    <ProjectReference Include="../Dokpod.Domain/Dokpod.Domain.csproj" />
  </ItemGroup>
</Project>
